// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ReportController from "./report_controller"
application.register("report", ReportController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import { initializeSearch } from "./search"
document.addEventListener('turbo:load', () => {
    document.addEventListener('shown.bs.modal', (event) => {
      if (event.target.querySelector('#artist-search')) {
        initializeSearch()
      }
    })
})